#spring:
#  jpa:
#  hibernate:
#    ddl-auto: create-drop
#  show-sql: true
#  datasource:
#    url: jdbc:sqlserver://PC-ORLANDO\SQLEXPRESS;databaseName=Prueba;
#    username: admin
#    password: admin1234
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver



spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
spring.datasource.url: jdbc:mysql://localhost:3306/store
spring.datasource.username: root
spring.datasource.password:
spring.jpa.show-sql : true